schema = 3

[mod]
  [mod.'github.com/Nadim147c/fang']
    version = 'v0.5.0-fork'
    hash = 'sha256-A0ZKLf4RC3ubboaQKHYx141yULNikLM3pgMj+TyEjp8='

  [mod.'github.com/adrg/xdg']
    version = 'v0.5.3'
    hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='

  [mod.'github.com/apache/arrow-go/v18']
    version = 'v18.5.1'
    hash = 'sha256-2q4JvRKNFg/QsF6zaNeibZd+lDIJLZdnUdQjS9+Yqa0='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/carapace-sh/carapace']
    version = 'v1.10.3'
    hash = 'sha256-dD0jQddLVwOVGVPhXTcPEAbdWXx65UW3xmsCEzoNrkI='

  [mod.'github.com/carapace-sh/carapace-shlex']
    version = 'v1.1.1'
    hash = 'sha256-XOMZOCUcpODDKp2E1FPUH9tBPkZTV5Vlr7XW40Q6dQw='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.3.2'
    hash = 'sha256-bmbfVhrituuloDzOnGHTUxhs2KyDRjUpgwznHQBdK00='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.0'
    hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='

  [mod.'github.com/charmbracelet/lipgloss/v2']
    version = 'v2.0.0-beta.3.0.20250917201909-41ff0bf215ea'
    hash = 'sha256-zUC6ck/MICubJ+9EYsT5A7hhtckndMSfFjFW6v7xVbo='

  [mod.'github.com/charmbracelet/log']
    version = 'v0.4.2'
    hash = 'sha256-3w1PCM/c4JvVEh2d0sMfv4C77Xs1bPa1Ea84zdynC7I='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20250915111650-81d4262876ef'
    hash = 'sha256-JYPRCGamorZGBSK1rWR8W740FB6os8EDgpDyPktDNEQ='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.10.1'
    hash = 'sha256-nY4zkUGnuD+Lczwt+NMXdQ38cAsy5mtxzXrFSJmR0E4='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.13'
    hash = 'sha256-ubgBd82jcS5L4i6rCFLOB1BXGrDEu6wWlciJA0gsH2g='

  [mod.'github.com/charmbracelet/x/exp/charmtone']
    version = 'v0.0.0-20250603201427-c31516f43444'
    hash = 'sha256-x6EfMobGGF31tnkjXuoGLxAa6V1ozsR2Z43TQu9/mX0='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.1'
    hash = 'sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/duckdb/duckdb-go-bindings']
    version = 'v0.10503.0'
    hash = 'sha256-z9e5iZ8Stxvr2nMsym5RrcPPP0dWWHBIFXMxrMMpGEA='

  [mod.'github.com/duckdb/duckdb-go-bindings/lib/darwin-amd64']
    version = 'v0.10503.0'
    hash = 'sha256-GSzz55KD9iNUxY3792Gly3/hrrb4yk3JFwFlN8gKlt8='

  [mod.'github.com/duckdb/duckdb-go-bindings/lib/darwin-arm64']
    version = 'v0.10503.0'
    hash = 'sha256-Vs+zBiFzvr3v7txmyKwSliTRZhHRUgvLKycy6JEovoA='

  [mod.'github.com/duckdb/duckdb-go-bindings/lib/linux-amd64']
    version = 'v0.10503.0'
    hash = 'sha256-uayno45e8+QFFXAVP+lh+4Q+UU1AJ4aFRjqn17xrD1U='

  [mod.'github.com/duckdb/duckdb-go-bindings/lib/linux-arm64']
    version = 'v0.10503.0'
    hash = 'sha256-zd0EeJtG521h/mRnNd0c2rZRAa6GRMTuMOFeO1oe+1w='

  [mod.'github.com/duckdb/duckdb-go-bindings/lib/windows-amd64']
    version = 'v0.10503.0'
    hash = 'sha256-3yBcwXuMnrRz4aZQ/K+zPZgqQ0ZD79SksBMpa0kk+e4='

  [mod.'github.com/duckdb/duckdb-go/v2']
    version = 'v2.10503.1'
    hash = 'sha256-yjFOJb9XC8tpVTC/KToT3cZrfYqZshnyOu1RdpRyDtE='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.9.0'
    hash = 'sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g='

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.0'
    hash = 'sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.5.0'
    hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

  [mod.'github.com/goccy/go-json']
    version = 'v0.10.5'
    hash = 'sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw='

  [mod.'github.com/google/flatbuffers']
    version = 'v25.12.19+incompatible'
    hash = 'sha256-NOYL9CWJgjdY1u4j/Ccyz2i50RjvZfNm/K+EFj7GIYk='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/klauspost/compress']
    version = 'v1.18.3'
    hash = 'sha256-rG6YIM3ePl2fIr26ornLxWH22jbvGuXr6T/PYdr4Ogw='

  [mod.'github.com/klauspost/cpuid/v2']
    version = 'v2.3.0'
    hash = 'sha256-50JhbQyT67BK38HIdJihPtjV7orYp96HknI2VP7A9Yc='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.16'
    hash = 'sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/mango']
    version = 'v0.1.0'
    hash = 'sha256-Xy63UxeZJMU4JlG6uuEpUeyxTGytx+NDbqCAgXpZrrU='

  [mod.'github.com/muesli/mango-cobra']
    version = 'v1.2.0'
    hash = 'sha256-26X9H9t2Z/kLII2n/Zd+D568H2rlbVJPS11jT25bdUA='

  [mod.'github.com/muesli/mango-pflag']
    version = 'v0.1.0'
    hash = 'sha256-qgUxVjVFmbcGjn8m58DRRu4hmYhirEUDy9TjkJYU8m4='

  [mod.'github.com/muesli/roff']
    version = 'v0.1.0'
    hash = 'sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/neurlang/wayland']
    version = 'v0.3.0'
    hash = 'sha256-PlgCFb6p9aMQZsu6bG7PC4YH99Dr6TM0sZOMDUPBN6w='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

  [mod.'github.com/pierrec/lz4/v4']
    version = 'v4.1.25'
    hash = 'sha256-rpGrxdd36HU2aFtYjLET24v9qmqexkhCGwfPGGRoId0='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/rogpeppe/go-internal']
    version = 'v1.14.1'
    hash = 'sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.11.0'
    hash = 'sha256-PUX8dzJtkD8YDZFNqpHnl4qgb0tE1W/DLnL7V+/d1z4='

  [mod.'github.com/sourcegraph/conc']
    version = 'v0.3.1-0.20240121214520-5f936abd7ae8'
    hash = 'sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.1'
    hash = 'sha256-OP6wdqk4dvBD8U5aicTkySHZ2s0LWnBo2TST2SmgcpM='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yalue/native_endian']
    version = 'v1.0.2'
    hash = 'sha256-NoxSGg8AQBZRttHiYRWyahLhYLLO+vjOeA18TxwX7Es='

  [mod.'github.com/zeebo/xxh3']
    version = 'v1.1.0'
    hash = 'sha256-UuyNDofnjry9qKddcVhkTZFYUXgCYoLuKmCoOcyd504='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260112195511-716be5621a96'
    hash = 'sha256-rWqwXzLvvhcI/ZkOQMqCXMKI5FAuHd9YNoKTXujmboA='

  [mod.'golang.org/x/mod']
    version = 'v0.32.0'
    hash = 'sha256-4gbgIqTOo0vcYV3l4MIwmT/h8H9PXmcfrJ3z4B26Zl0='

  [mod.'golang.org/x/net']
    version = 'v0.49.0'
    hash = 'sha256-arK6PWwO9tQUJVb57QXUEXfgcB6ISI6qjVB0eC4zcnw='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.40.0'
    hash = 'sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg='

  [mod.'golang.org/x/telemetry']
    version = 'v0.0.0-20260116145544-c6413dc483f5'
    hash = 'sha256-jTDg2UBAG4HZnw/XwwGd7zdDcn3s+lDEIg9LEymPmnM='

  [mod.'golang.org/x/text']
    version = 'v0.33.0'
    hash = 'sha256-XdA6D39ESuJkaaM/SRBnqZzjKUwi6Gbt1Si1nvauTr4='

  [mod.'golang.org/x/tools']
    version = 'v0.41.0'
    hash = 'sha256-/Plnksa1jSr4jYJc2oCH9fcjGbWocM7EYposMP0tScQ='

  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
