name := "yankd"
bin := "build" / name
tag := `git describe --long --tags --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'`
version := env("VERSION", tag)
user-local := `echo ~/.local`
prefix := absolute_path(env("PREFIX", user-local))

build-install:
    @just build
    @just install

install:
    install -Dm755 {{ bin }} "{{ prefix }}/bin/{{ name }}"
    install -Dm644 <({{ bin }} _carapace bash) "{{ prefix }}/share/bash-completion/completions/{{ name }}.bash"
    install -Dm644 <({{ bin }} _carapace fish) "{{ prefix }}/share/fish/vendor_completions.d/{{ name }}.fish"
    install -Dm644 <({{ bin }} _carapace zsh ) "{{ prefix }}/share/zsh/site-functions/_{{ name }}"

build:
    # Build for default os and arch
    @just compile "" ""

compile os arch:
    env \
      CGO_ENABLED=0 \
      GOOS="{{ os }}" \
      GOARCH="{{ arch }}" \
      go build -trimpath -ldflags '-s -w -X main.Version={{ version }}' -o {{ bin }}

watch:
  watchexec -e go -r --stop-signal 15 -- go run . daemon -vv

fmt:
  gofumpt -w .

generate:
  just generate-sqlc
  just generate-protocol

generate-protocol:
	@echo "Generating code using wayland-scanner!"
	@go run github.com/neurlang/wayland/cmd/wayland-scanner@latest \
		-i ./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml

	@echo "Formatting generated files..."
	@gofumpt -w ./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

	@echo "Fixing package name..."
	@sed -i 's/[Pp]ackage wlr/package protocol/' \
		./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

	@echo "Replacing header comment..."
	@sed -i "1,3c// Code generated by wayland-scanner. DO NOT EDIT.\n" \
		./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

generate-sqlc:
	@echo "Generating code using sqlc!"
	@sqlc generate

	@echo "Formatting generated files..."
	@gofumpt -w internal/db/sqlc/*.go

migration-create name:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations create "{{name}}" sql

migration-rollback:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations reset

migration-reset:
  just migration-rollback
  just migration-up

migration-up:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations up

migration-down:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations down

migration-redo:
  just migration-down
  just migration-up
