generate:
  generate-sqlc
  generate-protocol

generate-protocol:
	@echo "Generating code using wayland-scanner!"
	@go run github.com/neurlang/wayland/cmd/wayland-scanner@latest \
		-i ./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml

	@echo "Formatting generated files..."
	@gofumpt -w ./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

	@echo "Fixing package name..."
	@sed -i 's/[Pp]ackage wlr/package protocol/' \
		./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

	@echo "Replacing header comment..."
	@sed -i "1,3c// Code generated by wayland-scanner. DO NOT EDIT.\n" \
		./internal/wlr-data-control-unstable-v1/wlr-data-control-unstable-v1.xml.go

generate-sqlc:
	@echo "Generating code using sqlc!"
	@sqlc generate

	@echo "Fixing generated code..."
	@sed -i \
		-e 's/WHERE contents_fts.text MATCH ?/WHERE contents_fts MATCH ?/' \
		-e 's/SELECT text FROM contents_fts/SELECT rowid, rank FROM contents_fts/' \
	  -e 's/BestRank interface{}/BestRank float64/' \
		internal/db/sqlc/queries.sql.go

	@echo "Formatting generated files..."
	@gofumpt -w internal/db/sqlc/*.go

migration-create name:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations create "{{name}}" sql

migration-rollback:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations reset

migration-reset:
  just migration-rollback
  just migration-up

migration-up:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations up

migration-down:
  goose sqlite3 ./tmp/histroy.db -dir ./internal/db/sqlc/migrations down

migration-redo:
  just migration-down
  just migration-up
