// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/Nadim147c/yankd/internal/models"
)

type Content struct {
	ID     int64       `db:"id" json:"id"`
	Hash   models.Hash `db:"hash" json:"hash"`
	IsText bool        `db:"is_text" json:"is_text"`
	Blob   []byte      `db:"blob" json:"blob"`
}

type Entry struct {
	EventID   int64  `db:"event_id" json:"event_id"`
	MimeType  string `db:"mime_type" json:"mime_type"`
	ContentID int64  `db:"content_id" json:"content_id"`
}

type Event struct {
	ID              int64     `db:"id" json:"id"`
	PrimaryMimeType string    `db:"primary_mime_type" json:"primary_mime_type"`
	Time            time.Time `db:"time" json:"time"`
	Preview         string    `db:"preview" json:"preview"`
}
