// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/Nadim147c/yankd/internal/models"
)

type Data struct {
	ID     int64             `db:"id" json:"id"`
	Hash   models.Hash       `db:"hash" json:"hash"`
	IsText bool              `db:"is_text" json:"is_text"`
	Text   models.NullString `db:"text" json:"text"`
	Blob   []byte            `db:"blob" json:"blob"`
}

type DatasFt struct {
	Text string `db:"text" json:"text"`
}

type Entry struct {
	EventID  int64  `db:"event_id" json:"event_id"`
	MimeType string `db:"mime_type" json:"mime_type"`
	DataID   int64  `db:"data_id" json:"data_id"`
}

type Event struct {
	ID              int64     `db:"id" json:"id"`
	PrimaryMimeType string    `db:"primary_mime_type" json:"primary_mime_type"`
	Time            time.Time `db:"time" json:"time"`
}
