// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"strings"
	"time"

	"github.com/Nadim147c/yankd/internal/models"
)

const createData = `-- name: CreateData :one
INSERT INTO datas (hash, is_text, text, blob)
VALUES (?, ?, ?, ?)
RETURNING id, hash, is_text, text, blob
`

type CreateDataParams struct {
	Hash   models.Hash       `db:"hash" json:"hash"`
	IsText bool              `db:"is_text" json:"is_text"`
	Text   models.NullString `db:"text" json:"text"`
	Blob   []byte            `db:"blob" json:"blob"`
}

// CreateData
//
//	INSERT INTO datas (hash, is_text, text, blob)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, hash, is_text, text, blob
func (q *Queries) CreateData(ctx context.Context, arg CreateDataParams) (Data, error) {
	row := q.db.QueryRowContext(ctx, createData,
		arg.Hash,
		arg.IsText,
		arg.Text,
		arg.Blob,
	)
	var i Data
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.IsText,
		&i.Text,
		&i.Blob,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (event_id, mime_type, data_id)
VALUES (?, ?, ?)
RETURNING event_id, mime_type, data_id
`

type CreateEntryParams struct {
	EventID  int64  `db:"event_id" json:"event_id"`
	MimeType string `db:"mime_type" json:"mime_type"`
	DataID   int64  `db:"data_id" json:"data_id"`
}

// CreateEntry
//
//	INSERT INTO entries (event_id, mime_type, data_id)
//	VALUES (?, ?, ?)
//	RETURNING event_id, mime_type, data_id
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.EventID, arg.MimeType, arg.DataID)
	var i Entry
	err := row.Scan(&i.EventID, &i.MimeType, &i.DataID)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (primary_mime_type, time)
VALUES (?, ?)
RETURNING id, primary_mime_type, time
`

type CreateEventParams struct {
	PrimaryMimeType string    `db:"primary_mime_type" json:"primary_mime_type"`
	Time            time.Time `db:"time" json:"time"`
}

// CreateEvent
//
//	INSERT INTO events (primary_mime_type, time)
//	VALUES (?, ?)
//	RETURNING id, primary_mime_type, time
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.PrimaryMimeType, arg.Time)
	var i Event
	err := row.Scan(&i.ID, &i.PrimaryMimeType, &i.Time)
	return i, err
}

const deleteAllEvents = `-- name: DeleteAllEvents :execrows
DELETE FROM events
`

// DeleteAllEvents
//
//	DELETE FROM events
func (q *Queries) DeleteAllEvents(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEvents = `-- name: DeleteEvents :execrows
DELETE FROM events
WHERE id IN (/*SLICE:ids*/?)
`

// DeleteEvents
//
//	DELETE FROM events
//	WHERE id IN (/*SLICE:ids*/?)
func (q *Queries) DeleteEvents(ctx context.Context, ids []int64) (int64, error) {
	query := deleteEvents
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fullTextSearch = `-- name: FullTextSearch :many
WITH matched_datas AS (
  SELECT rowid, rank FROM datas_fts
  WHERE datas_fts MATCH ?
)
SELECT e.id, MIN(m.rank) AS best_rank
FROM matched_datas m
JOIN datas d ON d.id = m.rowid
JOIN entries en ON en.data_id = d.id
JOIN events e ON e.id = en.event_id
GROUP BY e.id
ORDER BY best_rank
`

type FullTextSearchRow struct {
	ID       int64   `db:"id" json:"id"`
	BestRank float64 `db:"best_rank" json:"best_rank"`
}

// FullTextSearch
//
//	WITH matched_datas AS (
//	  SELECT rowid, rank FROM datas_fts
//	  WHERE datas_fts MATCH ?
//	)
//	SELECT e.id, MIN(m.rank) AS best_rank
//	FROM matched_datas m
//	JOIN datas d ON d.id = m.rowid
//	JOIN entries en ON en.data_id = d.id
//	JOIN events e ON e.id = en.event_id
//	GROUP BY e.id
//	ORDER BY best_rank
func (q *Queries) FullTextSearch(ctx context.Context, text string) ([]FullTextSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, fullTextSearch, text)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FullTextSearchRow{}
	for rows.Next() {
		var i FullTextSearchRow
		if err := rows.Scan(&i.ID, &i.BestRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasByHash = `-- name: GetDatasByHash :many
SELECT id, hash, is_text, text, blob FROM datas
WHERE hash = ?
`

// GetDatasByHash
//
//	SELECT id, hash, is_text, text, blob FROM datas
//	WHERE hash = ?
func (q *Queries) GetDatasByHash(ctx context.Context, hash models.Hash) ([]Data, error) {
	rows, err := q.db.QueryContext(ctx, getDatasByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Data{}
	for rows.Next() {
		var i Data
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.IsText,
			&i.Text,
			&i.Blob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntries = `-- name: GetEntries :many
SELECT entries.event_id, entries.mime_type, entries.data_id, datas.id, datas.hash, datas.is_text, datas.text, datas.blob FROM entries
JOIN datas ON datas.id = entries.data_id
WHERE entries.event_id IN (/*SLICE:ids*/?)
`

type GetEntriesRow struct {
	EventID  int64             `db:"event_id" json:"event_id"`
	MimeType string            `db:"mime_type" json:"mime_type"`
	DataID   int64             `db:"data_id" json:"data_id"`
	ID       int64             `db:"id" json:"id"`
	Hash     models.Hash       `db:"hash" json:"hash"`
	IsText   bool              `db:"is_text" json:"is_text"`
	Text     models.NullString `db:"text" json:"text"`
	Blob     []byte            `db:"blob" json:"blob"`
}

// GetEntries
//
//	SELECT entries.event_id, entries.mime_type, entries.data_id, datas.id, datas.hash, datas.is_text, datas.text, datas.blob FROM entries
//	JOIN datas ON datas.id = entries.data_id
//	WHERE entries.event_id IN (/*SLICE:ids*/?)
func (q *Queries) GetEntries(ctx context.Context, ids []int64) ([]GetEntriesRow, error) {
	query := getEntries
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntriesRow{}
	for rows.Next() {
		var i GetEntriesRow
		if err := rows.Scan(
			&i.EventID,
			&i.MimeType,
			&i.DataID,
			&i.ID,
			&i.Hash,
			&i.IsText,
			&i.Text,
			&i.Blob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, primary_mime_type, time FROM events
WHERE id = ?
`

// GetEvent
//
//	SELECT id, primary_mime_type, time FROM events
//	WHERE id = ?
func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(&i.ID, &i.PrimaryMimeType, &i.Time)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, primary_mime_type, time FROM events
WHERE id IN (/*SLICE:ids*/?)
`

// GetEvents
//
//	SELECT id, primary_mime_type, time FROM events
//	WHERE id IN (/*SLICE:ids*/?)
func (q *Queries) GetEvents(ctx context.Context, ids []int64) ([]Event, error) {
	query := getEvents
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(&i.ID, &i.PrimaryMimeType, &i.Time); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastEvents = `-- name: GetLastEvents :many
SELECT id, primary_mime_type, time
FROM events
ORDER BY time DESC
LIMIT ?
`

// GetLastEvents
//
//	SELECT id, primary_mime_type, time
//	FROM events
//	ORDER BY time DESC
//	LIMIT ?
func (q *Queries) GetLastEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getLastEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(&i.ID, &i.PrimaryMimeType, &i.Time); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
