// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package binds

import (
	"gorm.io/cli/gorm/field"
)

var Clip = struct {
	ID       field.Number[uint]
	Time     field.Time
	Text     field.String
	Blob     field.Bytes
	Mime     field.String
	Metadata field.String
	URL      field.String
	BlobPath field.String
}{
	ID:       field.Number[uint]{}.WithColumn("id"),
	Time:     field.Time{}.WithColumn("time"),
	Text:     field.String{}.WithColumn("text"),
	Blob:     field.Bytes{}.WithColumn("blob"),
	Mime:     field.String{}.WithColumn("mime"),
	Metadata: field.String{}.WithColumn("metadata"),
	URL:      field.String{}.WithColumn("url"),
	BlobPath: field.String{}.WithColumn("blob_path"),
}
